### ISSUE TITLE
Compilation with -DCMAKE_BUILD_TYPE=Debug fails

### ISSUE THREAD

**Issue by gmarpons** [gmarpons/Crisp#16]
On branch get_rules_dir_at_runtime.

error: unable to load plugin
      '/home/gmarpons/llvm-cmake-debug/projects/crisp/lib/DeclExtractor/libdeclextractor.so':
      '/home/gmarpons/llvm-cmake-debug/projects/crisp/lib/DeclExtractor/libdeclextractor.so:
      undefined symbol: _ZN4llvm9DebugFlagE'
make[2]: **\* [lib/CrispClangPlugin/CMakeFiles/run_clang_decl_extractor.dir/ClangDeclarations.cpp.o] Error 1

**Comment by rizsotto** [comment]
It is there because your clang were compiled in release mode. Check this out http://llvm.org/docs/doxygen/html/Debug_8h_source.html The symbol is guarded by #ifndef NDEBUG, so you have no chance to have it when you compile against release mode llvm libs. Was able to make a debug build Crisp iff the clang was also a debug build.
